nameOverride: ""
fullnameOverride: ""
replicaCount: 2
image:
  repository: ghcr.io/kushalesh/api-gateway
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts: []
  tls: []
resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits:   { cpu: 500m, memory: 512Mi }
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
podDisruptionBudget:
  enabled: true
  minAvailable: 1
serviceAccount:
  create: true
  annotations: {}
  name: ""
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  fsGroup: 65532
  seccompProfile: { type: RuntimeDefault }
securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities: { drop: [ALL] }
serviceMonitor:
  enabled: true
  interval: 30s
  path: /metrics
env: []
