apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-staging

helmCharts:
  - name: microservices-app
    repo: ""
    version: 0.1.0
    releaseName: notification-service
    namespace: app-staging
    valuesInline:
      replicaCount: 2
      image:
        repository: ghcr.io/kushalesh/notification-service
        tag: "staging-latest"
      service:
        port: 5000
        targetPort: 5000
      serviceAccount:
        annotations:
          iam.gke.io/gcp-service-account: notification-service@my-gcp-project.iam.gserviceaccount.com
      env:
        - name: APP_VERSION
          value: "staging-latest"
        - name: ENV
          value: "staging"
